// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgd6gv-vT2o9aa3nSp_-urQwFMc8RJAE',
    appId: '1:388524370985:web:70672aa9210cf934928038',
    messagingSenderId: '388524370985',
    projectId: 'dreamtrace-ai-test',
    authDomain: 'dreamtrace-ai-test.firebaseapp.com',
    storageBucket: 'dreamtrace-ai-test.firebasestorage.app',
    measurementId: 'G-NDLN7XXL0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-RTkmeoEqPzuBMkgf0gtzF9Wgt_16NQ',
    appId: '1:388524370985:android:a4ab603ec2e54f97928038',
    messagingSenderId: '388524370985',
    projectId: 'dreamtrace-ai-test',
    storageBucket: 'dreamtrace-ai-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJT6ATE7K3WcWP08TN2a3w9vIkwoUCZU',
    appId: '1:388524370985:ios:3f462e579db3d9df928038',
    messagingSenderId: '388524370985',
    projectId: 'dreamtrace-ai-test',
    storageBucket: 'dreamtrace-ai-test.firebasestorage.app',
    iosBundleId: 'com.dreamtrace.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJT6ATE7K3WcWP08TN2a3w9vIkwoUCZU',
    appId: '1:388524370985:ios:1cf7a875e3d64797928038',
    messagingSenderId: '388524370985',
    projectId: 'dreamtrace-ai-test',
    storageBucket: 'dreamtrace-ai-test.firebasestorage.app',
    iosBundleId: 'com.example.dhikruLindaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgd6gv-vT2o9aa3nSp_-urQwFMc8RJAE',
    appId: '1:388524370985:web:838cbbf694c1f5e7928038',
    messagingSenderId: '388524370985',
    projectId: 'dreamtrace-ai-test',
    authDomain: 'dreamtrace-ai-test.firebaseapp.com',
    storageBucket: 'dreamtrace-ai-test.firebasestorage.app',
    measurementId: 'G-Q05S7P4RFE',
  );
}
